USE [master]
GO
/****** Object:  Database [ipsum]    Script Date: 09/08/2022 23:11:08 ******/
CREATE DATABASE [ipsum]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ipsum', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ipsum.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ipsum_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ipsum_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ipsum] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ipsum].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ipsum] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ipsum] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ipsum] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ipsum] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ipsum] SET ARITHABORT OFF 
GO
ALTER DATABASE [ipsum] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ipsum] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ipsum] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ipsum] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ipsum] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ipsum] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ipsum] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ipsum] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ipsum] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ipsum] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ipsum] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ipsum] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ipsum] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ipsum] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ipsum] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ipsum] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ipsum] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ipsum] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ipsum] SET  MULTI_USER 
GO
ALTER DATABASE [ipsum] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ipsum] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ipsum] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ipsum] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ipsum] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ipsum]
GO
/****** Object:  Table [dbo].[equipe]    Script Date: 09/08/2022 23:11:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[equipe](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[descricao] [varchar](200) NULL,
	[setor] [varchar](200) NULL,
	[observacao] [text] NOT NULL,
	[datahora_criacao] [datetime] NULL,
 CONSTRAINT [PK_equipe] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[funcionario]    Script Date: 09/08/2022 23:11:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[funcionario](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](200) NULL,
	[cargo] [varchar](200) NULL,
	[salario] [numeric](18, 10) NULL,
	[equipe] [int] NULL,
	[datahora_criacao] [datetime] NULL,
	[observacao] [text] NULL,
 CONSTRAINT [PK_funcionario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[funcionario]  WITH CHECK ADD  CONSTRAINT [FK_funcionario_equipe] FOREIGN KEY([equipe])
REFERENCES [dbo].[equipe] ([id])
GO
ALTER TABLE [dbo].[funcionario] CHECK CONSTRAINT [FK_funcionario_equipe]
GO
USE [master]
GO
ALTER DATABASE [ipsum] SET  READ_WRITE 
GO
